---
spring:
  application:
    name: task-service
  jpa:
    generate-ddl: true
security:
  basic:
    enabled: false
#logging:
#  level:
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
#    org.springframework: DEBUG

---
spring:
  profiles: local,local-mysql
  cloud:
    config:
      uri: http://localhost:8888

---
spring:
  profiles: local-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/amps
    username: root
    password: root
